services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: oasis_app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
    command: >
      sh -c "
        if [ -d '/app/app/db/migrations/versions' ] && [ -n "$(ls -A /app/app/db/migrations/versions/)" ]; then
          echo 'Applying migrations...' &&
          alembic upgrade head;
        else
          echo 'No migrations found. Please create migrations first.';
        fi &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - oasis_network

  public:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oasis_public
    volumes:
      - ./backend:/backend
    ports:
      - "3000:3000"
    command: uvicorn main_public:app --host 0.0.0.0 --port 3000 --reload
    env_file:
      - ./backend/.env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    networks:
      - oasis_network
    depends_on:
      - db

  internal:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: oasis_internal
    volumes:
      - ./backend:/backend
    ports:
      - "3001:3001"
    command: uvicorn main_internal:app --host 0.0.0.0 --port 3001 --reload
    env_file:
      - ./backend/.env
    networks:
      - oasis_network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: oasis_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - oasis_network
    env_file:
      - ./backend/.env

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: oasis_admin
    volumes:
      - ./admin:/admin
      - /admin/node_modules
      - /admin/.next
    ports:
      - "8081:8081"
    command: yarn dev --port 8081
    networks:
      - oasis_network

  wallet:
    build:
      context: ./wallet
      dockerfile: Dockerfile
    container_name: oasis_wallet
    volumes:
      - ./wallet:/wallet
    ports:
      - "3002:3002"
    command: uvicorn main:app --host 0.0.0.0 --port 3002 --reload
    networks:
      - oasis_network

  brain:
    build:
      context: ./brain
    container_name: oasis_brain
    volumes:
      - ./brain:/brain
    command: python main.py
    networks:
      - oasis_network

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: oasis_llm
    ports:
      - "11434:11434"
    networks:
      - oasis_network

  nginx:
    image: nginx:alpine
    container_name: oasis_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app
      - public
      - internal
      - admin
      - wallet
      - llm
    networks:
      - oasis_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: oasis_ngrok
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    command: start --all --config=/etc/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    env_file:
      - ./backend/.env
    depends_on:
      - nginx
    networks:
      - oasis_network

volumes:
  postgres_data:

networks:
  oasis_network:
    driver: bridge
