version: "3.8"

services:
  fastapi:
    build: .
    container_name: oasis_app
    volumes:
      - .:/app
      - ./data:/data
    ports:
      - "8000:8000"
    environment:
      - API_KEY=${API_KEY}
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
    command: >
      sh -c "
        if [ -d '/app/app/db/migrations/versions' ] && [ -n "$(ls -A /app/app/db/migrations/versions/)" ]; then
          echo 'Applying migrations...' &&
          alembic upgrade head;
        else
          echo 'No migrations found. Please create migrations first.';
        fi &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - oasis_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    container_name: oasis_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - fastapi
    networks:
      - oasis_network

  nginx:
    image: nginx:alpine
    container_name: oasis_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - fastapi
      - frontend
    networks:
      - oasis_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: oasis_ngrok
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - "4040:4040"
    command: start --all --config=/etc/ngrok.yml
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    env_file:
      - .env
    depends_on:
      - nginx
    networks:
      - oasis_network

  llm:
    build:
      context: ./llm
      dockerfile: Dockerfile
    container_name: oasis_llm
    ports:
      - "8001:11434"
    networks:
      - oasis_network

networks:
  oasis_network:
    driver: bridge
