"""Initial migration

Revision ID: c392aef17f29
Revises: 
Create Date: 2025-02-07 03:43:40.120442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c392aef17f29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_voice_segments_id', table_name='voice_segments')
    op.drop_table('voice_segments')
    op.drop_index('ix_motion_id', table_name='motion')
    op.drop_table('motion')
    op.drop_index('ix_gladia_responses_id', table_name='gladia_responses')
    op.drop_table('gladia_responses')
    op.drop_index('ix_speaker_clips_id', table_name='speaker_clips')
    op.drop_table('speaker_clips')
    op.drop_index('ix_vision_id', table_name='vision')
    op.drop_table('vision')
    op.drop_index('ix_audios_filename', table_name='audios')
    op.drop_index('ix_audios_id', table_name='audios')
    op.drop_table('audios')
    op.drop_index('ix_transcriptions_id', table_name='transcriptions')
    op.drop_table('transcriptions')
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_speakers_id', table_name='speakers')
    op.drop_index('ix_speakers_profile_id', table_name='speakers')
    op.drop_table('speakers')
    op.drop_index('ix_diarization_segments_id', table_name='diarization_segments')
    op.drop_table('diarization_segments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diarization_segments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audio_id', sa.INTEGER(), nullable=True),
    sa.Column('speaker', sa.VARCHAR(), nullable=True),
    sa.Column('start_time', sa.FLOAT(), nullable=True),
    sa.Column('end_time', sa.FLOAT(), nullable=True),
    sa.Column('confidence', sa.FLOAT(), nullable=True),
    sa.Column('raw_response', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diarization_segments_id', 'diarization_segments', ['id'], unique=False)
    op.create_table('speakers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('speaker_label', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_speakers_profile_id', 'speakers', ['profile_id'], unique=1)
    op.create_index('ix_speakers_id', 'speakers', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audio_id', sa.INTEGER(), nullable=True),
    sa.Column('conversation_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    op.create_table('transcriptions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('audio_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transcriptions_id', 'transcriptions', ['id'], unique=False)
    op.create_table('audios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=True),
    sa.Column('waveform', sa.BLOB(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audios_id', 'audios', ['id'], unique=False)
    op.create_index('ix_audios_filename', 'audios', ['filename'], unique=1)
    op.create_table('vision',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_data', sa.BLOB(), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vision_id', 'vision', ['id'], unique=False)
    op.create_table('speaker_clips',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audio_id', sa.INTEGER(), nullable=True),
    sa.Column('speaker', sa.VARCHAR(), nullable=True),
    sa.Column('waveform', sa.BLOB(), nullable=True),
    sa.Column('profile_id', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_speaker_clips_id', 'speaker_clips', ['id'], unique=False)
    op.create_table('gladia_responses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audio_id', sa.INTEGER(), nullable=True),
    sa.Column('response_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gladia_responses_id', 'gladia_responses', ['id'], unique=False)
    op.create_table('motion',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('motion_data', sa.BLOB(), nullable=True),
    sa.Column('timestamp', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_motion_id', 'motion', ['id'], unique=False)
    op.create_table('voice_segments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('audio_id', sa.INTEGER(), nullable=False),
    sa.Column('segment_id', sa.INTEGER(), nullable=False),
    sa.Column('waveform', sa.BLOB(), nullable=True),
    sa.Column('start_time', sa.INTEGER(), nullable=True),
    sa.Column('end_time', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['audio_id'], ['audios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_voice_segments_id', 'voice_segments', ['id'], unique=False)
    # ### end Alembic commands ###
